---
apiVersion: v1
kind: Secret
metadata:
  name: headscale-config
type: Opaque
stringData:
  config.yaml: |
{{- $config := .Values.headscale.config }}
{{- if $config.dns.manualNameservers.global }}
{{- $manualGlobal := splitList ";" $config.dns.manualNameservers.global }}
{{- $_ := set $config.dns.nameservers "global" $manualGlobal }}
{{- else }}
{{- $_ := set $config.dns.nameservers "global" $config.dns.nameservers.global }}
{{- end }}
{{- if $config.dns.manualNameservers.split }}
{{- $splitNameservers := dict }}
{{- $splitEntries := splitList "|" $config.dns.manualNameservers.split }}
{{- range $splitEntries }}
{{- $parts := splitList ":" . }}
{{- if eq (len $parts) 2 }}
{{- $domain := index $parts 0 }}
{{- $ips := splitList ";" (index $parts 1) }}
{{- $_ := set $splitNameservers $domain $ips }}
{{- end }}
{{- end }}
{{- $_ := set $config.dns.nameservers "split" $splitNameservers }}
{{- else if $config.dns.nameservers.split }}
{{- $_ := set $config.dns.nameservers "split" $config.dns.nameservers.split }}
{{- end }}
{{- $_ := unset $config.dns "manualNameservers" }}
{{- toYaml $config | nindent 4 }}
  {{- if .Values.headscale.oidc.enabled }}
    oidc:
      issuer: {{ .Values.headscale.oidc.issuer | quote }}
      client_id: {{ .Values.headscale.oidc.client_id | quote }}
      client_secret: {{ .Values.headscale.oidc.client_secret | required "headscale.oidc.client_secret is required when OIDC is enabled" | quote }}
      {{- if .Values.headscale.oidc.allowed_groups }}
      allowed_groups:
        {{- toYaml .Values.headscale.oidc.allowed_groups | nindent 8 }}
      {{- end }}
      {{- if .Values.headscale.oidc.allowed_domains }}
      allowed_domains:
        {{- toYaml .Values.headscale.oidc.allowed_domains | nindent 8 }}
      {{- end }}
      {{- if .Values.headscale.oidc.allowed_users }}
      allowed_users:
        {{- toYaml .Values.headscale.oidc.allowed_users | nindent 8 }}
      {{- end }}
      {{- if .Values.headscale.oidc.pkce.enabled }}
      pkce:
        enabled: {{ .Values.headscale.oidc.pkce.enabled | quote }}
        method: {{ .Values.headscale.oidc.pkce.method | quote }}
      {{- end }}
{{- end }}
