{{- if .Values.relay.enabled -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tailscale-relay
  labels:
    app: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      serviceAccountName: "tailscale-relay"
      {{- if .Values.relay.config.routes }}
      initContainers:
      - name: setup-routes
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          # Get default gateway automatically
          GATEWAY=$(ip route show default | awk '{print $3}' | head -1)
          echo "Using gateway: $GATEWAY"
          
          # Add routes for all configured networks
          {{- range $route := (split "," .Values.relay.config.routes) }}
          {{- $cleanRoute := trim $route }}
          echo "Adding route: {{ $cleanRoute }} via $GATEWAY"
          ip route add {{ $cleanRoute }} via $GATEWAY dev eth0 || echo "Route {{ $cleanRoute }} already exists or failed"
          {{- end }}
          
          echo "Route setup complete"
          ip route show
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
      {{- end }}
      containers:
      - name: tailscale
        image: {{ .Values.relay.image }}
        imagePullPolicy: Always
        env:
        {{- $extraArgs := list }}
        {{- if .Values.relay.config.login_server }}
        {{- $extraArgs = append $extraArgs (printf "--login-server=%s" .Values.relay.config.login_server) }}
        {{- end }}
        {{- if .Values.relay.config.advertise_exit_node }}
        {{- $extraArgs = append $extraArgs "--advertise-exit-node" }}
        {{- end }}
        {{- if .Values.relay.config.routes }}
        {{- $extraArgs = append $extraArgs (printf "--advertise-routes=%s" .Values.relay.config.routes) }}
        {{- end }}
        {{- if gt (len $extraArgs) 0 }}
        - name: TS_EXTRA_ARGS
          value: "{{ join " " $extraArgs }}"
        {{- end }}
        {{- if .Values.relay.config.exit_node }}
        - name: TS_EXIT_NODE
          value: "{{ .Values.relay.config.exit_node }}"
        {{- end }}
        {{- if .Values.relay.config.hostname }}
        - name: TS_HOSTNAME
          value: "{{ .Values.relay.config.hostname }}"
        {{- end }}
        {{- if .Values.relay.config.routes }}
        - name: TS_ROUTES
          value: "{{ .Values.relay.config.routes }}"
        {{- end }}
        {{- if .Values.relay.config.firewall_debug }}
        - name: TS_DEBUG_FIREWALL_MODE
          value: "{{ .Values.relay.config.firewall_debug }}"
        {{- end }}
        - name: TS_KUBE_SECRET
          value: "tailscale-auth"
        - name: TS_USERSPACE
          value: "false"
        {{- if .Values.relay.config.authKey }}
        - name: TS_AUTHKEY
          value: "{{ .Values.relay.config.authKey }}"
        {{- else }}
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
              optional: true
        {{- end }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        {{- if .Values.relay.pvc.enabled }}
        volumeMounts:
        - name: tailscale-data
          mountPath: /var/lib/tailscale
        {{- end }}
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
  {{- if .Values.relay.pvc.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: tailscale-data
    spec:
      accessModes:
        {{- range .Values.relay.pvc.accessModes }}
        - {{ . | quote }}
        {{- end }}
      resources:
        requests:
          storage: {{ .Values.relay.pvc.storage | quote }}
      {{- if .Values.relay.pvc.storageClassName }}
      storageClassName: {{ .Values.relay.pvc.storageClassName | quote }}
      {{- end }}
  {{- end }}
{{- end }}
